// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloWorld.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type HelloWorldRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HelloWorldRequest) Reset()         { *m = HelloWorldRequest{} }
func (m *HelloWorldRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldRequest) ProtoMessage()    {}
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{1}
}

func (m *HelloWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldRequest.Unmarshal(m, b)
}
func (m *HelloWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldRequest.Merge(m, src)
}
func (m *HelloWorldRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldRequest.Size(m)
}
func (m *HelloWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldRequest proto.InternalMessageInfo

func (m *HelloWorldRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type HelloWorldResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldResponse) Reset()         { *m = HelloWorldResponse{} }
func (m *HelloWorldResponse) String() string { return proto.CompactTextString(m) }
func (*HelloWorldResponse) ProtoMessage()    {}
func (*HelloWorldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{2}
}

func (m *HelloWorldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldResponse.Unmarshal(m, b)
}
func (m *HelloWorldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldResponse.Marshal(b, m, deterministic)
}
func (m *HelloWorldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldResponse.Merge(m, src)
}
func (m *HelloWorldResponse) XXX_Size() int {
	return xxx_messageInfo_HelloWorldResponse.Size(m)
}
func (m *HelloWorldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldResponse proto.InternalMessageInfo

func (m *HelloWorldResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type HelloWorldRepeatedRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	Repeat               int32     `protobuf:"varint,2,opt,name=repeat,proto3" json:"repeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HelloWorldRepeatedRequest) Reset()         { *m = HelloWorldRepeatedRequest{} }
func (m *HelloWorldRepeatedRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldRepeatedRequest) ProtoMessage()    {}
func (*HelloWorldRepeatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{3}
}

func (m *HelloWorldRepeatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldRepeatedRequest.Unmarshal(m, b)
}
func (m *HelloWorldRepeatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldRepeatedRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldRepeatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldRepeatedRequest.Merge(m, src)
}
func (m *HelloWorldRepeatedRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldRepeatedRequest.Size(m)
}
func (m *HelloWorldRepeatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldRepeatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldRepeatedRequest proto.InternalMessageInfo

func (m *HelloWorldRepeatedRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

func (m *HelloWorldRepeatedRequest) GetRepeat() int32 {
	if m != nil {
		return m.Repeat
	}
	return 0
}

type HelloWorldRepeatedResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldRepeatedResponse) Reset()         { *m = HelloWorldRepeatedResponse{} }
func (m *HelloWorldRepeatedResponse) String() string { return proto.CompactTextString(m) }
func (*HelloWorldRepeatedResponse) ProtoMessage()    {}
func (*HelloWorldRepeatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{4}
}

func (m *HelloWorldRepeatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldRepeatedResponse.Unmarshal(m, b)
}
func (m *HelloWorldRepeatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldRepeatedResponse.Marshal(b, m, deterministic)
}
func (m *HelloWorldRepeatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldRepeatedResponse.Merge(m, src)
}
func (m *HelloWorldRepeatedResponse) XXX_Size() int {
	return xxx_messageInfo_HelloWorldRepeatedResponse.Size(m)
}
func (m *HelloWorldRepeatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldRepeatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldRepeatedResponse proto.InternalMessageInfo

func (m *HelloWorldRepeatedResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type HelloWorldLongRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HelloWorldLongRequest) Reset()         { *m = HelloWorldLongRequest{} }
func (m *HelloWorldLongRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldLongRequest) ProtoMessage()    {}
func (*HelloWorldLongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{5}
}

func (m *HelloWorldLongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldLongRequest.Unmarshal(m, b)
}
func (m *HelloWorldLongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldLongRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldLongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldLongRequest.Merge(m, src)
}
func (m *HelloWorldLongRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldLongRequest.Size(m)
}
func (m *HelloWorldLongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldLongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldLongRequest proto.InternalMessageInfo

func (m *HelloWorldLongRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type HelloWorldLongResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldLongResponse) Reset()         { *m = HelloWorldLongResponse{} }
func (m *HelloWorldLongResponse) String() string { return proto.CompactTextString(m) }
func (*HelloWorldLongResponse) ProtoMessage()    {}
func (*HelloWorldLongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{6}
}

func (m *HelloWorldLongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldLongResponse.Unmarshal(m, b)
}
func (m *HelloWorldLongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldLongResponse.Marshal(b, m, deterministic)
}
func (m *HelloWorldLongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldLongResponse.Merge(m, src)
}
func (m *HelloWorldLongResponse) XXX_Size() int {
	return xxx_messageInfo_HelloWorldLongResponse.Size(m)
}
func (m *HelloWorldLongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldLongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldLongResponse proto.InternalMessageInfo

func (m *HelloWorldLongResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type HelloWorldEveryoneRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HelloWorldEveryoneRequest) Reset()         { *m = HelloWorldEveryoneRequest{} }
func (m *HelloWorldEveryoneRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldEveryoneRequest) ProtoMessage()    {}
func (*HelloWorldEveryoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{7}
}

func (m *HelloWorldEveryoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldEveryoneRequest.Unmarshal(m, b)
}
func (m *HelloWorldEveryoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldEveryoneRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldEveryoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldEveryoneRequest.Merge(m, src)
}
func (m *HelloWorldEveryoneRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldEveryoneRequest.Size(m)
}
func (m *HelloWorldEveryoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldEveryoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldEveryoneRequest proto.InternalMessageInfo

func (m *HelloWorldEveryoneRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type HelloWorldEveryoneResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldEveryoneResponse) Reset()         { *m = HelloWorldEveryoneResponse{} }
func (m *HelloWorldEveryoneResponse) String() string { return proto.CompactTextString(m) }
func (*HelloWorldEveryoneResponse) ProtoMessage()    {}
func (*HelloWorldEveryoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{8}
}

func (m *HelloWorldEveryoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldEveryoneResponse.Unmarshal(m, b)
}
func (m *HelloWorldEveryoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldEveryoneResponse.Marshal(b, m, deterministic)
}
func (m *HelloWorldEveryoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldEveryoneResponse.Merge(m, src)
}
func (m *HelloWorldEveryoneResponse) XXX_Size() int {
	return xxx_messageInfo_HelloWorldEveryoneResponse.Size(m)
}
func (m *HelloWorldEveryoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldEveryoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldEveryoneResponse proto.InternalMessageInfo

func (m *HelloWorldEveryoneResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type HelloWorldWithDeadlineRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HelloWorldWithDeadlineRequest) Reset()         { *m = HelloWorldWithDeadlineRequest{} }
func (m *HelloWorldWithDeadlineRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldWithDeadlineRequest) ProtoMessage()    {}
func (*HelloWorldWithDeadlineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{9}
}

func (m *HelloWorldWithDeadlineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldWithDeadlineRequest.Unmarshal(m, b)
}
func (m *HelloWorldWithDeadlineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldWithDeadlineRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldWithDeadlineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldWithDeadlineRequest.Merge(m, src)
}
func (m *HelloWorldWithDeadlineRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldWithDeadlineRequest.Size(m)
}
func (m *HelloWorldWithDeadlineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldWithDeadlineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldWithDeadlineRequest proto.InternalMessageInfo

func (m *HelloWorldWithDeadlineRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type HelloWorldWithDeadlineResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldWithDeadlineResponse) Reset()         { *m = HelloWorldWithDeadlineResponse{} }
func (m *HelloWorldWithDeadlineResponse) String() string { return proto.CompactTextString(m) }
func (*HelloWorldWithDeadlineResponse) ProtoMessage()    {}
func (*HelloWorldWithDeadlineResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06405d6227701fc8, []int{10}
}

func (m *HelloWorldWithDeadlineResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldWithDeadlineResponse.Unmarshal(m, b)
}
func (m *HelloWorldWithDeadlineResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldWithDeadlineResponse.Marshal(b, m, deterministic)
}
func (m *HelloWorldWithDeadlineResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldWithDeadlineResponse.Merge(m, src)
}
func (m *HelloWorldWithDeadlineResponse) XXX_Size() int {
	return xxx_messageInfo_HelloWorldWithDeadlineResponse.Size(m)
}
func (m *HelloWorldWithDeadlineResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldWithDeadlineResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldWithDeadlineResponse proto.InternalMessageInfo

func (m *HelloWorldWithDeadlineResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*HelloWorldRequest)(nil), "greet.HelloWorldRequest")
	proto.RegisterType((*HelloWorldResponse)(nil), "greet.HelloWorldResponse")
	proto.RegisterType((*HelloWorldRepeatedRequest)(nil), "greet.HelloWorldRepeatedRequest")
	proto.RegisterType((*HelloWorldRepeatedResponse)(nil), "greet.HelloWorldRepeatedResponse")
	proto.RegisterType((*HelloWorldLongRequest)(nil), "greet.HelloWorldLongRequest")
	proto.RegisterType((*HelloWorldLongResponse)(nil), "greet.HelloWorldLongResponse")
	proto.RegisterType((*HelloWorldEveryoneRequest)(nil), "greet.HelloWorldEveryoneRequest")
	proto.RegisterType((*HelloWorldEveryoneResponse)(nil), "greet.HelloWorldEveryoneResponse")
	proto.RegisterType((*HelloWorldWithDeadlineRequest)(nil), "greet.HelloWorldWithDeadlineRequest")
	proto.RegisterType((*HelloWorldWithDeadlineResponse)(nil), "greet.HelloWorldWithDeadlineResponse")
}

func init() { proto.RegisterFile("helloWorld.proto", fileDescriptor_06405d6227701fc8) }

var fileDescriptor_06405d6227701fc8 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5f, 0x4b, 0xc2, 0x50,
	0x14, 0x6f, 0x85, 0xa6, 0x27, 0xe8, 0xcf, 0x81, 0x44, 0x57, 0x86, 0x8d, 0x02, 0xa1, 0x10, 0xb1,
	0x1e, 0x7a, 0x8c, 0xb2, 0xf2, 0x41, 0x82, 0xd6, 0x83, 0x10, 0x84, 0xad, 0x3c, 0xcd, 0xc1, 0xdc,
	0xec, 0xee, 0x2a, 0xf4, 0x3d, 0xfb, 0x40, 0xb1, 0xeb, 0xe6, 0xee, 0x74, 0x3a, 0xd8, 0x93, 0xde,
	0x73, 0xce, 0xef, 0xcf, 0xbd, 0xe7, 0xc7, 0x60, 0x7f, 0x48, 0xb6, 0xed, 0xf6, 0x5c, 0x66, 0x0f,
	0x1a, 0x63, 0xe6, 0x72, 0x17, 0x73, 0x26, 0x23, 0xe2, 0xda, 0x23, 0x14, 0x9e, 0xfc, 0x3f, 0x96,
	0x63, 0x62, 0x15, 0xe0, 0xdb, 0x62, 0x1e, 0xef, 0x3b, 0xc6, 0x88, 0xca, 0x4a, 0x4d, 0xa9, 0x17,
	0xf5, 0xa2, 0xa8, 0x3c, 0x1b, 0x23, 0xc2, 0x23, 0x28, 0xda, 0x46, 0xd8, 0xdd, 0x14, 0xdd, 0x82,
	0x5f, 0xf0, 0x9b, 0xda, 0x2d, 0x1c, 0x74, 0xe6, 0x12, 0x3a, 0xfd, 0x4c, 0xc8, 0xe3, 0x78, 0x01,
	0x05, 0x33, 0x20, 0x17, 0x74, 0x3b, 0xad, 0xbd, 0x86, 0x28, 0x34, 0x42, 0x4d, 0x7d, 0x3e, 0xa0,
	0x5d, 0x02, 0xca, 0x0c, 0xde, 0xd8, 0x75, 0x3c, 0xc2, 0x12, 0xe4, 0x19, 0x79, 0x13, 0x9b, 0x07,
	0x7e, 0x82, 0x93, 0xf6, 0x01, 0x15, 0x79, 0x7a, 0x4c, 0x06, 0xa7, 0x4c, 0xba, 0x33, 0x05, 0x1f,
	0x2f, 0xee, 0x94, 0xd3, 0x83, 0x93, 0x76, 0x0d, 0x6a, 0x92, 0x42, 0x8a, 0xaf, 0x36, 0x1c, 0x46,
	0xa8, 0xae, 0xeb, 0x98, 0x99, 0xde, 0xa2, 0x09, 0xa5, 0x45, 0x96, 0x14, 0xdd, 0x8e, 0xfc, 0x1e,
	0x0f, 0x53, 0x62, 0xbf, 0xae, 0x43, 0x99, 0xb4, 0x63, 0xf7, 0x8e, 0x98, 0x52, 0xf4, 0xbb, 0x50,
	0x8d, 0x50, 0x3d, 0x8b, 0x0f, 0xdb, 0x64, 0x0c, 0x6c, 0x2b, 0xa3, 0x87, 0x1b, 0x38, 0x59, 0xc5,
	0xb6, 0xde, 0x47, 0xeb, 0x6f, 0x4b, 0x0e, 0xe2, 0x2b, 0xb1, 0xa9, 0xf5, 0x45, 0x78, 0x0f, 0x10,
	0x15, 0xb1, 0x1c, 0x08, 0x2f, 0x05, 0x56, 0xad, 0x24, 0x74, 0x66, 0x82, 0xda, 0x06, 0xbe, 0xc7,
	0x03, 0x3a, 0x0b, 0x04, 0xd6, 0x12, 0x20, 0xb1, 0x34, 0xaa, 0xa7, 0x6b, 0x26, 0x42, 0xf2, 0xa6,
	0x82, 0x2f, 0xb0, 0x1b, 0xdf, 0x39, 0x1e, 0x2f, 0x01, 0xa5, 0x40, 0xa9, 0xd5, 0x15, 0xdd, 0x90,
	0xb2, 0xae, 0x60, 0x5f, 0x76, 0x1c, 0xae, 0x32, 0xc1, 0xf1, 0x42, 0x5e, 0x12, 0x1c, 0x2f, 0xe6,
	0xc0, 0xa7, 0x6f, 0x2a, 0x68, 0xca, 0x39, 0x95, 0xf7, 0x84, 0x67, 0x4b, 0x14, 0x09, 0xa1, 0x50,
	0xcf, 0x53, 0xa6, 0x42, 0xb1, 0xbb, 0xed, 0xb7, 0x9c, 0xf8, 0x6c, 0x7d, 0xe6, 0xc5, 0xcf, 0xd5,
	0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x82, 0x29, 0xa2, 0x84, 0xd1, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloWorldServiceClient is the client API for HelloWorldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloWorldServiceClient interface {
	// Unary Operation
	HelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...grpc.CallOption) (*HelloWorldResponse, error)
	// Server Streaming
	HelloWorldRepeated(ctx context.Context, in *HelloWorldRepeatedRequest, opts ...grpc.CallOption) (HelloWorldService_HelloWorldRepeatedClient, error)
	// Client Streaming
	HelloWorldLong(ctx context.Context, opts ...grpc.CallOption) (HelloWorldService_HelloWorldLongClient, error)
	// Bidirectional Streaming
	HelloWorldEveryone(ctx context.Context, opts ...grpc.CallOption) (HelloWorldService_HelloWorldEveryoneClient, error)
	// Second Unary Operation to demonstrate Deadlines
	HelloWorldWithDeadline(ctx context.Context, in *HelloWorldWithDeadlineRequest, opts ...grpc.CallOption) (*HelloWorldWithDeadlineResponse, error)
}

type helloWorldServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloWorldServiceClient(cc *grpc.ClientConn) HelloWorldServiceClient {
	return &helloWorldServiceClient{cc}
}

func (c *helloWorldServiceClient) HelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...grpc.CallOption) (*HelloWorldResponse, error) {
	out := new(HelloWorldResponse)
	err := c.cc.Invoke(ctx, "/greet.HelloWorldService/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloWorldServiceClient) HelloWorldRepeated(ctx context.Context, in *HelloWorldRepeatedRequest, opts ...grpc.CallOption) (HelloWorldService_HelloWorldRepeatedClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloWorldService_serviceDesc.Streams[0], "/greet.HelloWorldService/HelloWorldRepeated", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloWorldServiceHelloWorldRepeatedClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HelloWorldService_HelloWorldRepeatedClient interface {
	Recv() (*HelloWorldRepeatedResponse, error)
	grpc.ClientStream
}

type helloWorldServiceHelloWorldRepeatedClient struct {
	grpc.ClientStream
}

func (x *helloWorldServiceHelloWorldRepeatedClient) Recv() (*HelloWorldRepeatedResponse, error) {
	m := new(HelloWorldRepeatedResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloWorldServiceClient) HelloWorldLong(ctx context.Context, opts ...grpc.CallOption) (HelloWorldService_HelloWorldLongClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloWorldService_serviceDesc.Streams[1], "/greet.HelloWorldService/HelloWorldLong", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloWorldServiceHelloWorldLongClient{stream}
	return x, nil
}

type HelloWorldService_HelloWorldLongClient interface {
	Send(*HelloWorldLongRequest) error
	CloseAndRecv() (*HelloWorldLongResponse, error)
	grpc.ClientStream
}

type helloWorldServiceHelloWorldLongClient struct {
	grpc.ClientStream
}

func (x *helloWorldServiceHelloWorldLongClient) Send(m *HelloWorldLongRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloWorldServiceHelloWorldLongClient) CloseAndRecv() (*HelloWorldLongResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloWorldLongResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloWorldServiceClient) HelloWorldEveryone(ctx context.Context, opts ...grpc.CallOption) (HelloWorldService_HelloWorldEveryoneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloWorldService_serviceDesc.Streams[2], "/greet.HelloWorldService/HelloWorldEveryone", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloWorldServiceHelloWorldEveryoneClient{stream}
	return x, nil
}

type HelloWorldService_HelloWorldEveryoneClient interface {
	Send(*HelloWorldEveryoneRequest) error
	Recv() (*HelloWorldEveryoneResponse, error)
	grpc.ClientStream
}

type helloWorldServiceHelloWorldEveryoneClient struct {
	grpc.ClientStream
}

func (x *helloWorldServiceHelloWorldEveryoneClient) Send(m *HelloWorldEveryoneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloWorldServiceHelloWorldEveryoneClient) Recv() (*HelloWorldEveryoneResponse, error) {
	m := new(HelloWorldEveryoneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloWorldServiceClient) HelloWorldWithDeadline(ctx context.Context, in *HelloWorldWithDeadlineRequest, opts ...grpc.CallOption) (*HelloWorldWithDeadlineResponse, error) {
	out := new(HelloWorldWithDeadlineResponse)
	err := c.cc.Invoke(ctx, "/greet.HelloWorldService/HelloWorldWithDeadline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloWorldServiceServer is the server API for HelloWorldService service.
type HelloWorldServiceServer interface {
	// Unary Operation
	HelloWorld(context.Context, *HelloWorldRequest) (*HelloWorldResponse, error)
	// Server Streaming
	HelloWorldRepeated(*HelloWorldRepeatedRequest, HelloWorldService_HelloWorldRepeatedServer) error
	// Client Streaming
	HelloWorldLong(HelloWorldService_HelloWorldLongServer) error
	// Bidirectional Streaming
	HelloWorldEveryone(HelloWorldService_HelloWorldEveryoneServer) error
	// Second Unary Operation to demonstrate Deadlines
	HelloWorldWithDeadline(context.Context, *HelloWorldWithDeadlineRequest) (*HelloWorldWithDeadlineResponse, error)
}

// UnimplementedHelloWorldServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloWorldServiceServer struct {
}

func (*UnimplementedHelloWorldServiceServer) HelloWorld(ctx context.Context, req *HelloWorldRequest) (*HelloWorldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}
func (*UnimplementedHelloWorldServiceServer) HelloWorldRepeated(req *HelloWorldRepeatedRequest, srv HelloWorldService_HelloWorldRepeatedServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloWorldRepeated not implemented")
}
func (*UnimplementedHelloWorldServiceServer) HelloWorldLong(srv HelloWorldService_HelloWorldLongServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloWorldLong not implemented")
}
func (*UnimplementedHelloWorldServiceServer) HelloWorldEveryone(srv HelloWorldService_HelloWorldEveryoneServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloWorldEveryone not implemented")
}
func (*UnimplementedHelloWorldServiceServer) HelloWorldWithDeadline(ctx context.Context, req *HelloWorldWithDeadlineRequest) (*HelloWorldWithDeadlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorldWithDeadline not implemented")
}

func RegisterHelloWorldServiceServer(s *grpc.Server, srv HelloWorldServiceServer) {
	s.RegisterService(&_HelloWorldService_serviceDesc, srv)
}

func _HelloWorldService_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServiceServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.HelloWorldService/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServiceServer).HelloWorld(ctx, req.(*HelloWorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloWorldService_HelloWorldRepeated_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloWorldRepeatedRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloWorldServiceServer).HelloWorldRepeated(m, &helloWorldServiceHelloWorldRepeatedServer{stream})
}

type HelloWorldService_HelloWorldRepeatedServer interface {
	Send(*HelloWorldRepeatedResponse) error
	grpc.ServerStream
}

type helloWorldServiceHelloWorldRepeatedServer struct {
	grpc.ServerStream
}

func (x *helloWorldServiceHelloWorldRepeatedServer) Send(m *HelloWorldRepeatedResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _HelloWorldService_HelloWorldLong_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloWorldServiceServer).HelloWorldLong(&helloWorldServiceHelloWorldLongServer{stream})
}

type HelloWorldService_HelloWorldLongServer interface {
	SendAndClose(*HelloWorldLongResponse) error
	Recv() (*HelloWorldLongRequest, error)
	grpc.ServerStream
}

type helloWorldServiceHelloWorldLongServer struct {
	grpc.ServerStream
}

func (x *helloWorldServiceHelloWorldLongServer) SendAndClose(m *HelloWorldLongResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloWorldServiceHelloWorldLongServer) Recv() (*HelloWorldLongRequest, error) {
	m := new(HelloWorldLongRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HelloWorldService_HelloWorldEveryone_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloWorldServiceServer).HelloWorldEveryone(&helloWorldServiceHelloWorldEveryoneServer{stream})
}

type HelloWorldService_HelloWorldEveryoneServer interface {
	Send(*HelloWorldEveryoneResponse) error
	Recv() (*HelloWorldEveryoneRequest, error)
	grpc.ServerStream
}

type helloWorldServiceHelloWorldEveryoneServer struct {
	grpc.ServerStream
}

func (x *helloWorldServiceHelloWorldEveryoneServer) Send(m *HelloWorldEveryoneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloWorldServiceHelloWorldEveryoneServer) Recv() (*HelloWorldEveryoneRequest, error) {
	m := new(HelloWorldEveryoneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HelloWorldService_HelloWorldWithDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorldWithDeadlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServiceServer).HelloWorldWithDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.HelloWorldService/HelloWorldWithDeadline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServiceServer).HelloWorldWithDeadline(ctx, req.(*HelloWorldWithDeadlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloWorldService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.HelloWorldService",
	HandlerType: (*HelloWorldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _HelloWorldService_HelloWorld_Handler,
		},
		{
			MethodName: "HelloWorldWithDeadline",
			Handler:    _HelloWorldService_HelloWorldWithDeadline_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HelloWorldRepeated",
			Handler:       _HelloWorldService_HelloWorldRepeated_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HelloWorldLong",
			Handler:       _HelloWorldService_HelloWorldLong_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "HelloWorldEveryone",
			Handler:       _HelloWorldService_HelloWorldEveryone_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloWorld.proto",
}
